### ISSUE TITLE
Sort by File Order(unsorted) doesn't work

### ISSUE THREAD

**Issue by xanharris** [mpcjanssen/simpletask-android#248]
After upgrading to v5.4.0 and later, I found that my task list sort order has changed by itself without any modification on my part. I investigated and found that the sort by "File Order (Unsorted)" no longer works whether in ascending or descending order.

I am using the file order to implement the Final Version time management by Mark Forster which has worked really well. So my question is: Is this an intentional change or is it a regression bug?

Thanks and keep up the good work!

**Comment by mpcjanssen** [comment]
This should have been fixed in 5.4.3 can you check?

**Comment by xanharris** [comment]
I tried it using v5.4.3 and it doesn't work. I checked my todo.txt file directly and the order is correct. FYI, my sorting criteria is: 
1. Completed
2. By List
3. File Order (Unsorted)
4. By Priority
5. By Creation date
6. Threshold date in future
7. By due date
8. By threshold date
9. By Tag
10. Alphabetical

Changing the sort direction for File Order doesn't change anything. As a workaround, I change the sort direction for By Creation date which only works if there's one task per day. When there are more, they will be sorted alphabetically (For those task in the same day).

**Comment by mpcjanssen** [comment]
I can reproduce the issue. I will look for a fix ASAP.

**Comment by mpcjanssen** [comment]
The issue is fixed in 5.4.5. Out of curiosity how do you use file order to
implement Final Version?

**Comment by xanharris** [comment]
Glad you asked :-)

Final Version algorithm requires tasks to be added from top to bottom. This is where File Order comes in as I'm taking advantage of the fact that new items are appended to todo.txt. In case you're interested, here's how I use SimpleTask for Final Version:

1. In main screen, ensure that list is sorted by File Order ascending
2. Enter the tasks in no particular order (Due dates & related features are not used)
3. Select the first task in the list, then walking down the list, select task based on the question: What do I want to do more than x?
4. Once done, assign a tag to the selected chain of tasks (e.g. Now)
5. Create a widget on the Homescreen, showing only "Now" tag and with the File Order in descending/reverse order. This will show the tasks in the order to be done

This shows the flexibility of your app to implement something other than GTD or MYN. One thing I would like to see is some statistics page on completed tasks (e.g. min/avg/max tasks done per day/week/month) so I understand my limits and how to improve on it. All the information is already in the todo.txt file, just need to calculate and present it :-)

**Comment by xanharris** [comment]
I just tested with v5.4.5 this morning. 
The File Order sort does respond, but there is still an issue: Sorting by file order works only when opening a txt file. But when adding new tasks at run time, it doesn't work.

**Details**
When I add a new task to the list, it is not added at the bottom, but rather somewhere near the top in some strange order. I tried opening another txt file and coming back to my original file. The file order is correct in this case.

**Comment by mpcjanssen** [comment]
OK I will investigate.

**Comment by mpcjanssen** [comment]
Very smart way of implementing FV BTW. It's always nice to see how others use the flexibility.

**Comment by mpcjanssen** [comment]
Could you check with the version at http://mpcjanssen.nl/files/simpletask/latest ?

**Comment by mpcjanssen** [comment]
wait for confirmation that it's fixed

**Comment by xanharris** [comment]
I just tested it from the link you gave. It's working fine now.

Thanks for such a responsive fix! :-) 
BTW, I'm a developer myself & I appreciate it.

**Comment by mpcjanssen** [comment]
Thanks for the detailed report.
